// courses.data.ts
import type { ExtendedCourse } from '@/interfaces/extended-course';

export const data: Array<ExtendedCourse> = [
  {
    id: 1,
    photo: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    courseName: 'General English Course – 11 Months',
    courseDescription: 'The General English course in the UK is designed for individuals who want to improve their language skills for various purposes, including academic, professional, and social communication.',
    courseBulletPoints: [
      'Duration: 11 Months',
      'Lessons Per Week: 5',
      'Hours Per Week: 15',
      'Class Time: MON to FRI From 10 AM-1 PM',
      'Suitable For: Education, Work or Socializing',
      'Level: Beginner to Advance',
      'Registration Fee: £300 (Non-refundable)',
      'Course Fee: £4500',
    ],
  },
  {
    id: 2,
    photo: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    courseName: 'IELTS Preparation Course – 11 Months',
    courseDescription: 'By taking this program, you will be equipped to take the International English Language Testing System (IELTS) Exam, which can help you achieve a good score that will benefit your future studies.',
    courseBulletPoints: [
      'Duration: 11 Months',
      'Start Date: First Monday Of Each Month',
      'Lessons Per Week: 5',
      'Hours Per Week: 15',
      'Class Time: MON to FRI From 10 AM-1 PM',
      'Suitable For: Education, Work or Socializing',
      'Level: Beginner to Advance',
      'Registration Fee: £300 (Non refundable)',
      'Course Fee: £5000',
    ],
  },
  {
    id: 3,
    photo: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    courseName: 'Business English Course – 6 Months',
    courseDescription: 'Business English Course is designed to help students develop and enhance their language skills in the context of professional settings. This course focuses on improving English proficiency in',
    courseBulletPoints: [
      'Duration: 6 Months',
      'Lessons Per Week: 5',
      'Hours Per Week: 15',
      'Class Time: MON to FRI From 10 AM-1 PM',
      'Suitable For: Education, Work or Socializing',
      'Level: Certificate',
      'Registration Fee: £300 (Non refundable)',
      'Course Fee: £3500',
    ],
  },
  {
    id: 4,
    photo: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    courseName: 'Business English Course for University Entrance – 11 Months',
    courseDescription: 'Business English Course for University Entrance is designed to help learners from basic to advance levels to improve their English language skills specifically for university entrance exams like',
    courseBulletPoints: [
      'Duration: 11 Months',
      'Lessons Per Week: 5',
      'Hours Per Week: 15',
      'Class Time: MON to FRI From 10 AM-1 PM',
      'Suitable For: Education, Work or Socializing',
      'Qualification Level: Certificate',
      'Reg Fee: £300',
      'Course Fee: £4500 (inc reg fee)',
    ],
  },
];