import type { DescriptiveCourse } from '@/interfaces/descriptive-course'

export const data: Array<DescriptiveCourse> = [
  {
    id: 1,
    cover: '/images/courses/course-1.png',
    title: 'General English Course',
    duration: '11 Months',
    description: 'The General English course in the UK is designed for individuals who want to improve their language skills for various purposes, including academic, professional, and social communication.',
    lessonsPerWeek: 5,
    hoursPerWeek: 15,
    classTime: 'MON to FRI From 10 AM-1 PM',
    suitableFor: 'Education, Work or Socializing',
    level: 'Beginner to Advance',
    registerationFee: '£300 (Non-refundable)',
    price: '£5500'
  },
  {
    id: 2,
    cover: '/images/courses/course-2.png',
    title: 'IELTS Preparation Course',
    duration: '11 Months',
    description: 'By taking this program, you will be equipped to take the International English Language Testing System (IELTS) Exam, which can help you achieve a good score that will benefit your future studies.',
    lessonsPerWeek: 5,
    hoursPerWeek: 15,
    classTime: 'MON to FRI From 10 AM-1 PM',
    suitableFor: 'Education, Work or Socializing',
    level: 'Beginner to Advance',
    registerationFee: '£300 (Non-refundable)',
    price: '£5500'
  },
  {
    id: 3,
    cover: '/images/courses/course-3.png',
    title: 'Business English Course',
    duration: '11 Months',
    description: 'Business English Course is designed to help students develop and enhance their language skills in the context of professional settings. This course focuses on improving English proficiency in',
    lessonsPerWeek: 5,
    hoursPerWeek: 15,
    classTime: 'MON to FRI From 10 AM-1 PM',
    suitableFor: 'Education, Work or Socializing',
    level: 'Certificate',
    registerationFee: '£300 (Non-refundable)',
    price: '£5500'
  },
  {
    id: 4,
    cover: '/images/courses/course-4.png',
    title: 'Principles of Customer Service',
    duration: '3 Weeks',
    description: 'In order to have a truly successful business, you need to provide good customer service. Handling a business’s issues in a professional and courteous manner is an essential day-to-day task.',
    lessonsPerWeek: 5,
    hoursPerWeek: 15,
    classTime: 'MON to FRI From 10 AM-1 PM',
    suitableFor: 'Education, Work or Socializing',
    level: 'Certificate',
    registerationFee: '£300 (Non-refundable)',
    price: '£3500'
  },
  {
    id: 5,
    cover: '/images/courses/course-5.png',
    title: 'Principles of Business Administration',
    duration: '3 Weeks',
    description: 'With an estimated 5.5 million private sector businesses in the UK, it’s imperative to learn the basic principles of business administration. Despite the recent economic difficulties, the trend',
    lessonsPerWeek: 5,
    hoursPerWeek: 15,
    classTime: 'MON to FRI From 10 AM-1 PM',
    suitableFor: 'Education, Work or Socializing',
    level: 'Certificate',
    registerationFee: '£300 (Non-refundable)',
    price: '£3500'
  },
  {
    id: 6,
    cover: '/images/courses/course-6.png',
    title: 'Principles of Team Leading',
    duration: '3 Weeks',
    description: 'Strong team leadership is essential for providing guidance, direction and instruction within a group and inevitably leads to more effective teamwork and more motivated employees',
    lessonsPerWeek: 5,
    hoursPerWeek: 15,
    classTime: 'MON to FRI From 10 AM-1 PM',
    suitableFor: 'Education, Work or Socializing',
    level: 'Certificate',
    registerationFee: '£300 (Non-refundable)',
    price: '£3500'
  },
  {
    id: 7,
    cover: '/images/courses/course-7.png',
    title: 'A2 Test',
    duration: '4 Months',
    description: '',
    lessonsPerWeek: 0,
    hoursPerWeek: 0,
    classTime: '',
    suitableFor: '',
    level: 'N/A',
    registerationFee: '',
    price: '£300'
  },
  {
    id: 8,
    cover: '/images/courses/course-8.png',
    title: 'Driving Theory Test',
    duration: '4 Months',
    description: '',
    lessonsPerWeek: 0,
    hoursPerWeek: 0,
    classTime: '',
    suitableFor: '',
    level: 'N/A',
    registerationFee: '',
    price: '£400'
  },
  {
    id: 9,
    cover: '/images/courses/course-9.png',
    title: 'Life In The Uk Test',
    duration: '6 Weeks',
    description: '',
    lessonsPerWeek: 0,
    hoursPerWeek: 0,
    classTime: '',
    suitableFor: '',
    level: 'N/A',
    registerationFee: '',
    price: '£400'
  },
  {
    id: 10,
    cover: '/images/courses/course-10.png',
    title: 'B1 Test',
    duration: '4 Months',
    description: '',
    lessonsPerWeek: 0,
    hoursPerWeek: 0,
    classTime: '',
    suitableFor: '',
    level: 'N/A',
    registerationFee: '',
    price: '£300'
  }
]